version: "3.8"

services:
  traefik:
    image: "traefik:v2.9"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public
      - internal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/datadisk/traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "/mnt/datadisk/traefik/acme.json:/acme.json"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  public:
    external: true
  internal:
    external: true
    
    
